### ISSUE TITLE
Naming issue in 'grupo03-m1'

### ISSUE THREAD

**Issue by rcastill** [rcastill/inf323-utfsm-grupo03#10]
Se detectó cuando fue imposible instalar `setroubleshoot` y `setools` en la máquina señalada debido a errores de nombre.

El error de yum estaba asociado a `curl` (ejemplo: `curl: (6) Could not resolve host: google.com; Unknown error`)

Se intentó hacer modificaciones sobre el archivo `/etc/resolv.conf` (está vacío) sin éxito.

Nos llamó la atención que `/etc/resolv.conf` dice estar generado por `NetworkManager`. Al final será utilizado?

**Comment by mosoriob** [comment]
Aplique el cambio necesario para resolver problema. 
Hacer modificaciones sobre el archivo /etc/resolv.conf, es una buena opción para iniciar.
