### ISSUE TITLE
Problema resuelto

### ISSUE THREAD

**Issue by mosoriob** [rcastill/inf323-utfsm-grupo03#19]
El problema de la mañana, esta resuelto, sinceramente no estoy seguro de la razón (si la encuentro, avisaré)

Pueden ver los cambios que realice con 

```
[root@grupo03-m1 etc]# git diff
```

**Comment by DVillegasA** [comment]
Estimado, mientras trabajábamos nos dimos cuenta que el problema no esta resuelto (o por alguna razón se volvió a echar a perder), ya que la pagina sigue sin mostrar el PHP. Según el error log, no es capaz de abrir el archivo correspondiente a index, alegando que no existe, por lo que puede ser un problema de permisos.
