### ISSUE TITLE
Problema: xtrabackup_binlog_info faltante

### ISSUE THREAD

**Issue by DVillegasA** [rcastill/inf323-utfsm-grupo03#23]
Al hacer el innobackupex, no se esta generando el archivo xtrabackup_binlog_info.

**Comment by DVillegasA** [comment]
Probé ejecutando el innobackupex usando al usuario root, pero aun así no me crea el archivo.

**Comment by mosoriob** [comment]
Estimado,

No tiene log binario, la replicación necesita log_bin. Slide 3 de la presentación de replicación.

![screen shot 2017-11-13 at 9 20 46 pm](https://user-images.githubusercontent.com/2365990/32756390-90fdf55c-c8b8-11e7-8c9a-4c90f2313774.png)

**Comment by DVillegasA** [comment]
Ahí lo resolvi, no habia habilitado bin log en el .cnf, Muchas gracias!
