### ISSUE TITLE
Levantar jenkins utilizando Docker

### ISSUE THREAD

**Issue by mosoriob** [rcastill/inf323-utfsm-grupo03#25]
<a href="https://github.com/sirspock"><img src="https://avatars0.githubusercontent.com/u/2365990?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sirspock](https://github.com/sirspock)**
_Wednesday Nov 22, 2017 at 02:35 GMT_
_Originally opened as https://github.com/sirspock/inf323/issues/28_

----

Utilizando la documentación, levantar jenkins que sea utilizando como CI para la construcción de sus imágenes

Tareas:
- Levantar jenkins. Siga la guía hasta el paso 3.

Documentación
- [https://www.katacoda.com/courses/jenkins/build-docker-images](https://www.katacoda.com/courses/jenkins/build-docker-images)

**Comment by rcastill** [comment]
Intentando levantar jenkins, no logramos exponerlo a la interfaz pública (connection refused). Se hicieron muchas pruebas:

- Se agregaron las reglas para abrir los puertos al firewall en ambas zonas
- Se bajó el firewall
- Se bajó el firewall + selinux
- Se bajó el firewall + selinux + nginx

Nada parece funcionar, sin embargo, agregando los puertos al firewall parece ser la manera correcta de solucionar el problema ya que se verificó su funcionamiento accediendo desde otro nodo en la red privada.

Nuestra teoría es que existe un firewall adicional sobre el que no tenemos acceso.
